# CNN Project-MNIST-Handwritten Digits-Dataset

In [5]:
#The MNIST dataset is a collection of 70,000 handwritten digits (0-9).
#It contains 60,000 training images and 10,000 testing images, each of which is a grayscale image of size 28x28 pixels.

In [6]:
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPool2D, Flatten, Dropout, Dense

In [7]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [8]:
X_train.shape

(60000, 28, 28)

In [9]:
y_train.shape

(60000,)

In [10]:
X_test.shape

(10000, 28, 28)

In [11]:
y_test.shape

(10000,)

In [12]:
X_train = X_train.reshape((X_train.shape[0], X_train.shape[1], X_train.shape[2],1))
X_test = X_test.reshape((X_test.shape[0], X_test.shape[1], X_test.shape[2], 1))

In [13]:
print("the new shape of Training data:", X_train.shape)
print("the new shape of Test data:", X_test.shape)

the new shape of Training data: (60000, 28, 28, 1)
the new shape of Test data: (10000, 28, 28, 1)


# Normalization of Data

In [14]:
X_train = X_train/255
X_test = X_test/255

In [15]:
X_train

array([[[[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        ...,

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]]],


       [[[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        ...,

        [[0.],
 

# Introduce the model

In [16]:
# Defining the model (sequential)
model = Sequential()

# Above code creates an empty model

# Add Convolution Layer

In [19]:
model.add(Conv2D(32, (3, 3), activation = 'relu', input_shape=(28,28,1)))

In [20]:
model.add(MaxPool2D(2,2))

# Add Fully Connected Layer(Dense Layer)

In [21]:
model.add(Flatten())

In [22]:
model.add(Dense(100, activation = 'relu'))

In [25]:
model.add(Dense(10, activation= 'softmax'))

In [29]:
model.compile(loss = 'sparse_categorical_crossentropy', optimizer = 'adam', metrics= ['accuracy'])

In [30]:
model.fit(X_train, y_train, epochs = 10, validation_data = (X_test, y_test))

Epoch 1/10


2024-12-20 16:58:47.036542: W external/local_xla/xla/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 188160000 exceeds 10% of free system memory.


   2/1875 ━━━━━━━━━━━━━━━━━━━━ 2:50 91ms/step - accuracy: 0.0391 - loss: 2.3223 

2024-12-20 16:58:51.610958: W external/local_xla/xla/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 22999680 exceeds 10% of free system memory.
2024-12-20 16:58:51.611586: W external/local_xla/xla/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 22999680 exceeds 10% of free system memory.
2024-12-20 16:58:51.713019: W external/local_xla/xla/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 22999680 exceeds 10% of free system memory.
2024-12-20 16:58:51.714957: W external/local_xla/xla/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 22999680 exceeds 10% of free system memory.


1875/1875 ━━━━━━━━━━━━━━━━━━━━ 125s 65ms/step - accuracy: 0.8933 - loss: 0.3446 - val_accuracy: 0.9837 - val_loss: 0.0505
Epoch 2/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 121s 65ms/step - accuracy: 0.9836 - loss: 0.0520 - val_accuracy: 0.9856 - val_loss: 0.0436
Epoch 3/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 119s 53ms/step - accuracy: 0.9901 - loss: 0.0318 - val_accuracy: 0.9891 - val_loss: 0.0334
Epoch 4/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 126s 44ms/step - accuracy: 0.9924 - loss: 0.0250 - val_accuracy: 0.9895 - val_loss: 0.0306
Epoch 5/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 53s 28ms/step - accuracy: 0.9938 - loss: 0.0190 - val_accuracy: 0.9879 - val_loss: 0.0427
Epoch 6/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 46s 24ms/step - accuracy: 0.9952 - loss: 0.0142 - val_accuracy: 0.9903 - val_loss: 0.0338
Epoch 7/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 48s 26ms/step - accuracy: 0.9963 - loss: 0.0109 - val_accuracy: 0.9914 - val_loss: 0.0284
Epoch 8/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 67s 36ms/step - accuracy: 0.9971 - loss: 

In [55]:
y_pred=model.predict(X_test)

313/313 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step


In [56]:
y_pred

array([[9.89044035e-15, 8.12015081e-15, 1.15322221e-13, ...,
        9.99999940e-01, 6.51036968e-18, 1.65022659e-13],
       [1.12845842e-13, 1.97131822e-09, 9.99999940e-01, ...,
        3.15186353e-17, 1.01133102e-10, 7.15765079e-22],
       [7.53612277e-12, 9.99999702e-01, 6.81357526e-10, ...,
        4.72465622e-08, 3.15378812e-09, 1.16081025e-11],
       ...,
       [1.92026786e-17, 1.95921881e-12, 1.07181360e-13, ...,
        7.44109581e-13, 4.02202195e-11, 6.03526154e-14],
       [2.39487936e-15, 7.77816412e-20, 2.15322868e-21, ...,
        3.76506765e-18, 9.40360151e-11, 2.13075472e-17],
       [1.05349089e-08, 7.15264521e-15, 6.77232487e-15, ...,
        3.93728790e-18, 3.52343960e-07, 1.99790442e-16]], dtype=float32)

In [57]:
X_test.shape

(10000, 28, 28, 1)

In [58]:
y_pred.shape

(10000, 10)

In [59]:
y_pred[0]   #Zero percent chance that this no. could be any no.

array([9.8904403e-15, 8.1201508e-15, 1.1532222e-13, 5.1103918e-13,
       1.0357355e-12, 1.3236260e-14, 7.2183929e-20, 9.9999994e-01,
       6.5103697e-18, 1.6502266e-13], dtype=float32)

In [64]:
y_pred[1]   #100%chance that this no. is 7.probability 1 means all the other probability should be zero.

array([1.1284584e-13, 1.9713182e-09, 9.9999994e-01, 9.7273018e-15,
       5.3920615e-17, 5.3102219e-19, 7.8194667e-10, 3.1518635e-17,
       1.0113310e-10, 7.1576508e-22], dtype=float32)

In [65]:
y_test[1]

2

In [66]:
y_test[0]

7

In [67]:
model.evaluate(X_test, y_test)

313/313 ━━━━━━━━━━━━━━━━━━━━ 8s 25ms/step - accuracy: 0.9872 - loss: 0.0574


[0.042638376355171204, 0.9900000095367432]

In [68]:
y_test

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [69]:
y.shape

(10000, 10)

In [72]:
X_test.shape

(10000, 28, 28, 1)

In [73]:
y_pred.shape

(10000, 10)